pref("extensions.zotero-bridge.obsidian.vaultPath", "");
pref("extensions.zotero-bridge.obsidian.vaultName", "");
pref("extensions.zotero-bridge.obsidian.folder", "Zotero");
pref("extensions.zotero-bridge.obsidian.filenameFormat", "citekey");
pref("extensions.zotero-bridge.obsidian.createBase", true);
pref("extensions.zotero-bridge.includeNotes", true);
pref("extensions.zotero-bridge.notion.database", "");
pref("extensions.zotero-bridge.notion.synthesisParent", "");
pref("extensions.zotero-bridge.routing.rules", "[]");
pref("extensions.zotero-bridge.llm.enabled", true);
pref("extensions.zotero-bridge.llm.provider", "anthropic");
pref("extensions.zotero-bridge.llm.anthropicModel", "claude-opus-5-5");
pref("extensions.zotero-bridge.llm.effort", "medium");
pref("extensions.zotero-bridge.llm.openaiModel", "gpt-5.5");
pref("extensions.zotero-bridge.llm.openaiBaseURL", "");
pref("extensions.zotero-bridge.llm.fullTextLimit", "150000");
// Scanned PDFs without a text layer are sent to the AI as a file, up to these limits (content/scanned.js)
pref("extensions.zotero-bridge.llm.sendScannedPDF", true);
pref("extensions.zotero-bridge.llm.pdfMaxMB", "20");
pref("extensions.zotero-bridge.llm.pdfMaxPages", "100");
pref("extensions.zotero-bridge.llm.systemPrompt", "");
pref("extensions.zotero-bridge.llm.synthesisPrompt", "");
pref("extensions.zotero-bridge.autoSync", false);
// API keys and the Notion token are kept in the login manager (content/secrets.js), not here
pref("extensions.zotero-bridge.usage.ledger", "{}");
pref("extensions.zotero-bridge.usage.prices", "");
pref("extensions.zotero-bridge.export.autoUpdate", false);
pref("extensions.zotero-bridge.export.bibtex", false);
pref("extensions.zotero-bridge.batch.pending", "");
